<script>
  export let key = "";
  const refDict = {
    introduction: "Section 1",
    background: "Section 2",
    "background-sonification": "Section 2.1",
    "background-toolkits": "Section 2.2",
    "background-grammar": "Section 2.3",
    gaps: "Section 3",
    consideration: "Section 4",
    grammar: "Section 5",
    "grammar-walkthrough": "Section 5.1",
    "grammar-stream": "Section 5.2",
    "grammar-data": "Section 5.3",
    "grammar-tone": "Section 5.4",
    "grammar-encoding": "Section 5.5",
    "grammar-encoding-scale": "Section 5.5.1",
    "grammar-composition": "Section 5.6",
    "grammar-composition-repeat": "Section 5.6.1",
    "grammar-composition-concat": "Section 5.6.2",
    "grammar-configuration": "Section 5.7",
    compiler: "Section 6",
    "compiler-preset": "Section 6.1",
    "compiler-specAPI": "Section 6.2",
    "compiler-queue": "Section 6.3",
    "compiler-player": "Section 6.4",
    "compiler-extension": "Section 6.5",
    demonstration: "Section 7",
    "demonstration-example": "Section 7.1",
    "demonstration-example-sparsity": "Section 7.1.1",
    "demonstration-example-kde": "Section 7.1.2",
    "demonstration-example-fit": "Section 7.1.3",
    "demonstration-replication": "Section 7.2",
    "demonstration-replication-narrative": "Section 7.2.1",
    "demonstration-replication-reader": "Section 7.2.2",
    "demonstration-replication-gunman": "Section 7.2.3",
    discussion: "Section 8",
    "discussion-hurdle": "Section 8.1",
    "discussion-potential": "Section 8.2",
    "discussion-future": "Section 8.3",
    "discussion-limitations": "Section 8.4",
    conclusion: "Section 9",
    appendix: "Appendix",
    "appendix-tone": "Appendix A.1",
    "appendix-encoding": "Appendix A.2",
    "appendix-encoding-time": "Appendix A.2.1",
    "appendix-encoding-channel": "Appendix A.2.2",
    "appendix-encoding-reference": "Appendix A.2.3",
    "appendix-encoding-inline": "Appendix A.2.4",
    "tab-comparison": "Table 1",
    "tab-grammar-walkthrough-tab": "Table 2",
    "tab-grammar-walkthrough": "Table 3",
    "tab-grammar-repeat1": "Table 4",
    "tab-grammar-repeat2": "Table 5",
    "tab-compiler-scale": "Table 6",
    "tab-demo-sparsity": "Table 7",
    "tab-demo-kde-data": "Table 8",
    "tab-demo-kde": "Table 9",
    "tab-demo-fit": "Table 10",
    "fig-grammar-formal": "Figure 1",
    "fig-demo-narrative": "Figure 2",
    "fig-demo-reader": "Figure 3",
    "fig-demo-gunman": "Figure 4",
  };
</script>

<a href={"#" + key}>{refDict[key] || "?"}</a>
