export const dataset_list = [
  'airports.csv',
  'flights-5k.json',
  'points.json',
  'annual-precip.json',
  'flights-airport.csv',
  'political-contributions.json',
  'anscombe.json',
  'football.json',
  'population.json',
  'barley.json',
  'gapminder-health-income.csv',
  'population_engineers_hurricanes.csv',
  'birdstrikes.csv',
  'gapminder.json',
  'seattle-weather-hourly-normals.csv',
  'budget.json',
  'github.csv',
  'seattle-weather.csv',
  'budgets.json',
  'income.json',
  'sp500-2000.csv',
  'burtin.json',
  'iowa-electricity.csv',
  'sp500.csv',
  'cars.json',
  'jobs.json',
  'stocks.csv',
  'co2-concentration.csv',
  'la-riots.csv',
  'udistrict.json',
  'countries.json',
  'londonBoroughs.json',
  'unemployment-across-industries.json',
  'crimea.json',
  'londonCentroids.json',
  'uniform-2d.json',
  'disasters.csv',
  'londonTubeLines.json',
  'us-10m.json',
  'driving.json',
  'lookup_groups.csv',
  'us-employment.csv',
  'earthquakes.json',
  'lookup_people.csv',
  'us-state-capitals.json',
  'flare-dependencies.json',
  'miserables.json',
  'volcano.json',
  'flare.json',
  'monarchs.json',
  'weather.csv',
  'flights-10k.json',
  'movies.json',
  'weather.json',
  'flights-200k.arrow',
  'normal-2d.json',
  'wheat.json',
  'flights-200k.json',
  'obesity.json',
  'windvectors.csv',
  'flights-20k.json',
  'ohlc.json',
  'world-110m.json',
  'flights-2k.json',
  'penguins.json',
  'zipcodes.csv',
  'flights-3m.csv',
  'platformer-terrain.json'
].map((d) => {
  let s = d.split(".");
  return {
    name: s[0],
    filename: d,
    ext: s[1]
  }
}).filter(d => {
  return ["csv", "json"].includes(d.ext);
});

export const NOM = "nominal", ORD = "ordinal", QUANT = "quantitative", TMP = "temporal";